spring:
  application:
    name: service-a


server:
  port: 57200

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true
    # healthcheck:
    #   enabled: true

ribbon:
    eureka:
        enabled: true

