spring:
  application:
    name: eureka
  cloud:
    config:
          server:
            git:
              uri: http://gitlab.lotus.com/lotus/config
              #repos:
              #  - patterns: multi-repo-demo-*
              #    uri: https://github.lotus.com/lotus/config

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/